version: '3.8'

services:
  api:
    # Build the Docker image using the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile

    # Assign a name to the built Docker image
    image: malicious_backlink_predict_ai_api_image_v1

    # Set a name for the running container
    container_name: malicious_backlink_predict_ai_api_container_v1

    # Mount local folders/files into the container
    volumes:
      # Mount the Homepage_Cache directory
      - ./app/homepage_cache:/app/app/homepage_cache
      # Mount the log file
      - ./app/logs:/app/app/logs

    # Ports
    ports:
      - "8000:8000"

    # Enable GPU access
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    # Specify the runtime for NVIDIA GPU support
    # runtime: nvidia

    # Set environment variables for NVIDIA GPU usage and JVM
    environment:
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - JVM_PATH=/usr/lib/jvm/java-21-openjdk-amd64/lib/server/libjvm.so